# Configuration for Alacritty, the GPU enhanced terminal emulator.
shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 200
    lines: 50
  padding:
    x: 5
    y: 5
  decorations: none

scrolling:
  history: 90000
  multiplier: 3

font:
  normal:
    family: MesloLGS NF
    style: Regular
  bold:
    family: MesloLGS NF
    style: Bold
  italic:
    family: MesloLGS NF
    style: Italic
  bold_italic:
    family: MesloLGS NF
    style: Bold Italic
  size: 10.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

# Colors
colors:
  # Default colors
  primary:
    background: '#333333'
    foreground: '#F2F2F2'

  # Normal colors
  normal:
    black: '#333333'
    red: '#CC0000'
    green: '#4E9A06'
    yellow: '#C4A000'
    blue: '#3465A4'
    magenta: '#75507B'
    cyan: '#06989A'
    white: '#D3D7CF'

  # Bright colors
  bright:
    black: '#88807C'
    red: '#F15D22'
    green: '#73C48F'
    yellow: '#FFCE51'
    blue: '#48B9C7'
    magenta: '#AD7FA8'
    cyan: '#34E2E2'
    white: '#EEEEEC'

cursor:
  style: Block
  unfocused_hollow: true

background_opacity: 0.95
theme: Pop!-OS
